name: tdythunderbolt
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8101366094779223
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.75
  lightness: 0.1496350965462625
  saturation: 0.3125
  rhythmicContrast: 0.8205973338335752
purpose: []
